// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

function initNavigation() {
  var sidenav = document.getElementById("mySidenav");
  var openBtn = document.getElementById("openBtn");
  var closeBtn = document.getElementById("closeBtn");
  var overlay = document.getElementById("sidenavOverlay");
  var burgerIcon = openBtn ? openBtn.querySelector(".burger-icon") : null;

  if (!sidenav || !openBtn || !closeBtn) return;

  function openNav() {
    sidenav.classList.add("active");
    if (overlay) overlay.classList.add("active");
    if (burgerIcon) burgerIcon.classList.add("active");
    document.body.style.overflow = "hidden";
  }

  function closeNav() {
    sidenav.classList.remove("active");
    if (overlay) overlay.classList.remove("active");
    if (burgerIcon) burgerIcon.classList.remove("active");
    document.body.style.overflow = "";
  }

  openBtn.onclick = openNav;
  closeBtn.onclick = closeNav;
  if (overlay) overlay.onclick = closeNav;

  // Navbar scroll effect
  var navbar = document.querySelector(".navbar-lewagon");
  if (navbar) {
    window.addEventListener("scroll", function() {
      if (window.scrollY > 50) {
        navbar.classList.add("scrolled");
      } else {
        navbar.classList.remove("scrolled");
      }
    });
  }

  // IntersectionObserver for scroll animations
  var animatedElements = document.querySelectorAll(
    ".animate-fade-in-up, .animate-fade-in, .animate-slide-in-left, .animate-scale-in"
  );

  if (animatedElements.length > 0 && "IntersectionObserver" in window) {
    animatedElements.forEach(function(el) {
      el.style.opacity = "0";
    });

    var observer = new IntersectionObserver(function(entries) {
      entries.forEach(function(entry) {
        if (entry.isIntersecting) {
          entry.target.style.opacity = "";
          entry.target.style.animationPlayState = "running";
          observer.unobserve(entry.target);
        }
      });
    }, { threshold: 0.1 });

    animatedElements.forEach(function(el) {
      el.style.animationPlayState = "paused";
      el.style.opacity = "0";
      observer.observe(el);
    });
  }

  // Stagger clothe-cards
  var cards = document.querySelectorAll(".clothe-card");
  cards.forEach(function(card, index) {
    card.style.animationDelay = (index * 0.08) + "s";
  });
}

document.addEventListener("DOMContentLoaded", initNavigation);
document.addEventListener("turbo:load", initNavigation);
