[build]
  command = "apt-get update && apt-get install -y build-essential libpq-dev && bundle config build.pg --with-pg-config=/opt/homebrew/bin/pg_config && bundle install"
  publish = "public"

[build.environment]
  BUNDLE_PATH = "vendor/bundle"
