meta_name: "Tudo Bem Maman"
meta_title: "From student lover in Portugal to everywhere !"
meta_description: "Inspired by phonecalls between a mother and a student who left to study in portugal and living his best life !"
meta_image: "surf-tbm.png" # should exist in `app/assets/images/`
